### ISSUE TITLE
TimeDoser stops working after a while without warning or user action

### ISSUE THREAD

**Issue by ghost** [DaniGuardiola/TimeDoser#11]
This appears to be a slightly different issue from the one submitted by ayooby (#9). TimeDoser worked flawlessly for months. Something changed in the past couple of months. Here's the scenario: I start the timer and set to work. Later, I notice it's been a while since I started the timer and shouldn't it be time for a break by now? I check TimeDoser and find the same thing ayooby sees. However, I haven't stopped the timer since I started it. I have to restart the app to get it to work again.

![timedoser](https://user-images.githubusercontent.com/12194458/28166145-d550cd6c-67a4-11e7-8a67-47c161c1b164.png)

I've tried reinstalling many, many times. It's happened with different versions of Chrome, so I think it's a TimeDoser issue, not an issue with Chrome.

This is a real problem for me. I do tech support and am on my computer most days for six or seven hours at a time. I have strict orders from my physical therapist to get up and stretch periodically. Because I tend to get lost in my work, I rely on TimeDoser to tell me when to take a break. Now I find I'm working an hour or more straight through because TimeDoser has silently stopped. I usually don't notice even when I keep the timer window visible (which I usually don't, because I work on a laptop and tend to keep Chrome maximized).
I've tried other timer apps and extensions. TimeDoser really is the best I've found. But the way it is now, it's completely useless to me. If you could make this a priority, I'd be very grateful. Thanks!

**Comment by DaniGuardiola** [comment]
@rhanajoy TimeDoser v2 is being retired, so I'm closing all issues. v3 is in the works, and it should replace v2 once I'm done. Thanks for your interest!
