### ISSUE TITLE
stop working with errors

### ISSUE THREAD

**Issue by doublefint** [DaniGuardiola/TimeDoser#12]
view/timer.html, line 1286
>Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

view/timer.js:1
> Uncaught TypeError: document.registerElement is not a function

**Comment by PandiyanCool** [comment]
One of my favorite chrome app. Waiting for the fixes, so that I can use it daily.

**Comment by DaniGuardiola** [comment]
@doublefint @PandiyanCool TimeDoser v2 is being retired, so I'm closing all issues. v3 is in the works, and it should replace v2 once I'm done. Thanks for your interest!
