### ISSUE TITLE
Font too large

### ISSUE THREAD

**Issue by orschiro** [DaniGuardiola/TimeDoser#2]
Hi @DaniGuardiola,

Many thanks for TimeDoser. This is a beautiful app that helps me to become aware of the time I actually spend in front of a computer and how I use it.

This app is close to perfect and nicely integrates into my elementary OS system. One issue, however, is related to a too large font. Only a cosmetic issue but yet worth mentioning, I suppose:

![screenshot from 2015-02-23 11 39 26](https://cloud.githubusercontent.com/assets/170947/6326361/291939a0-bb51-11e4-8aee-72a19baf42ef.png)

**Comment by DaniGuardiola** [comment]
Thanks! I'm very busy lately, but I really want to work again on TimeDoser... It is a big update so it will take a while... When I have some time I will release a small update fixing some bugs like this one.

**Comment by orschiro** [comment]
Great to hear. Thanks for taking your time to improve TimeDoser!

**Comment by DaniGuardiola** [comment]
Hey @orschiro, the redesign is already in progress. Check it out in the dev version: https://chrome.google.com/webstore/detail/timedoser/cagliknhkebcbddgkjglcbjmiffhdaag
Thanks, closing this.

**Comment by orschiro** [comment]
@DaniGuardiola 

Thanks a lot for the update! :)
