### ISSUE TITLE
Doesn't stick anymore on 2nd screen

### ISSUE THREAD

**Issue by thomykay** [DaniGuardiola/TimeDoser#3]
With the new version TimeDoser does not stick anymore on my second screen which I'm using for notifications, messaging etc. Whenever I move the window to the second screen and release it it moves back to the 1st screen.

Expectation: The window sticks to the edges of the current screen.

**Comment by DaniGuardiola** [comment]
Thanks for submitting the bug. As I stated on the other one, this has moved to https://github.com/DaniGuardiola/TimeDoser-small, but no problem.

About the sticking, it should stick to any border only if close enough. Can you send me a video?
