### ISSUE TITLE
TimeDoser window should not take focus when coming to top.

### ISSUE THREAD

**Issue by thomykay** [DaniGuardiola/TimeDoser#4]
It's more and more annoying that the TimeDoser window takes the focus when coming to top to notify the user.

Expectation: The window comes to top without taking the focus, mouse and text focus stay where they are. Midterm: TimeDoser should use Chrome notifications.

**Comment by DaniGuardiola** [comment]
Hi @thomykay, thanks for submitting the bug!
The TimeDoser Mini code (standard TimeDoser) has moved to https://github.com/DaniGuardiola/TimeDoser-small, but I will work on this bug anyway.

"The window comes to top without taking the focus, mouse and text focus stay where they are."
This is not possible, I can't do that. I will search for other option, or just remove it as other people also complained about it.

"TimeDoser should use Chrome notifications."
It does, to enable check the configuration option :)

**Comment by DaniGuardiola** [comment]
It has been fixed in last version
