### ISSUE TITLE
Minor CSS fix on alert box

### ISSUE THREAD

**Issue by gichuwil** [DaniGuardiola/TimeDoser#5]
This tool is just what i needed for productivity

"Time to work" text appears to be overflowing. The ..break text does not show. Maybe its a font-size issue?

![capture](https://cloud.githubusercontent.com/assets/1228073/9060114/7a9a5240-3ab9-11e5-8e15-37603b6dd31c.PNG)

**Comment by DaniGuardiola** [comment]
Should be fixed now, can you try @gichuwil ?
