### ISSUE TITLE
Add task support

### ISSUE THREAD

**Issue by DaniGuardiola** [DaniGuardiola/TimeDoser#6]
##

**Comment by darzo27** [comment]
I love the programme and prefer it to any of the other 'time management' apps I've tried. If it's able to still be so simplistic AND great-looking, then this surely needs to be implemented! @DaniGuardiola

**Comment by DaniGuardiola** [comment]
Working on it for a year now, I couldn't find the perfect way there. Has to be perfect. Nothing less, nothing more. :P

**Comment by darzo27** [comment]
I agree, it's the only sentiment to have towards your work.

**Comment by DaniGuardiola** [comment]
Stay tuned.
