### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by agrueneberg** [DaniGuardiola/TimeDoser#8]
Hi Dani,

great work on TimeDoser, it's my favorite Pomodoro tool out there! The only feature I am missing are shortcuts. It would be nice to be able to start the timer, for example, using the spacebar.

Cheers,
Alex
##

**Comment by DaniGuardiola** [comment]
Well you currently can use shortcuts BUT i'm gonna remove them as some were causing trouble to other users. Will study the feature and re-implement it in the future in a way that works for everyone :)

By the moment, check chrome://extensions (at the bottom there's an option to configure app shortcuts)

Thanks for your feedback!

**Comment by agrueneberg** [comment]
Oh, sweet, I've been using a couple of extension shortcuts that are registered there for a while now without knowing that they can be changed in that dialog! Unfortunately, the default shortcuts for TimeDoser don't seem to work for me on the Linux version of Chromium 47.0.2526.106 (64-bit) as well. Maybe because the shortcuts are already in use? I'm actually not sure if global shortcuts (or even the "in Chrome" ones) are a good fit for an app like TimeDoser. I was thinking more about something like https://github.com/ccampbell/mousetrap if that works with Chrome apps.
