### ISSUE TITLE
Timer will not working after start stop

### ISSUE THREAD

**Issue by ayooby** [DaniGuardiola/TimeDoser#9]
If we start timer and then stop it and then start it, the app doesn't show counter.

![Screen-shot](https://cloud.githubusercontent.com/assets/11707675/23585633/7c9a56ce-0198-11e7-9464-a51c463a2ded.png)

**Comment by DaniGuardiola** [comment]
@ayooby TimeDoser v2 is being retired, so I'm closing all issues. v3 is in the works, and it should replace v2 once I'm done. Thanks for your interest!
